# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: shreve.dev
environment: development

author: 
  name: Eric Shreve
  email: eric@shreve.dev
description: >- # this means to ignore newlines until "baseurl:"
  A blog about software development, technology, and other things that interest me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shreve.dev" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: "G-XG2C3GM9NW"

# Build settings
remote_theme: jekyll/minima

show_excerpts: true
tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag
tag_page_data:
  sitemap: false

permalink: none
paginate: false

# Build settings
minima:
  skin: dark

  social_links:
    - { platform: github, user_url: "https://github.com/ecshreve" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/ecshreve" }
    - { platform: email, user_url: "mailto:eric@shreve.dev"}
    - { platform: download, user_url: "/assets/files/ecshreve-resume.pdf"}
    
plugins:
  - jekyll-feed
  - jekyll/tagging
  - jekyll-remote-theme
  - jekyll-sitemap

header_pages:
  - pages/about.md
  - pages/blog.md
  - pages/tags.md


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - TODO
  - tasks.toml
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
