
[[task]]
id = "build"
type = "short"
cmd = "bundle exec jekyll build"

[[task]]
id = "serve"
type = "long"
triggers = ["build"]
cmd = "bundle exec jekyll serve --watch"

[[task]]
id = "serve-drafts"
type = "short"
watch = ["_config.yml"]
cmd = """
  bundle exec jekyll serve --drafts
"""

[[task]]
id = "setup"
type = "short"
cmd = """
  brew install ruby
  export PATH="/usr/local/opt/ruby/bin:$PATH"
  source ~/.zshrc
  gem install jekyll bundler
  bundle install
  bundle exec jekyll build
  bundle exec jekyll serve --watch
"""

[[task]]
id = "serve-and-watch"
type = "long"
cmd = """
  bundle exec jekyll serve --watch
  """
